#!/usr/bin/env python3
"""
md_to_warehouse.py
Wraps cron research markdown/HTML into styled HTML for vadapayasam.github.io/warehouse/sketch/
NEVER regenerates body content — only wraps/inlines CSS.
"""

import pathlib
import re
import shutil
import subprocess
import sys
import markdown

BASE_DIR = pathlib.Path.home() / "Projects" / "vadapayasam.github.io"
OUTPUT_DIR = BASE_DIR / "sketch"

def slugify(name):
    s = name.strip().lower().replace(' ', '-')
    s = re.sub(r'[^a-z0-9_-]', '', s)
    s = s[:100].strip('-')
    return s if s else 'untitled'

TITLE_RE = re.compile(r"^# (.+)$", re.MULTILINE)
DATE_STAMP = re.compile(r"[A-Za-z]{3}\s+\d{1,2},\s+\d{4}")

CSS = """
:root{font:18px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,"Hanken Grotesk",sans-serif}
*{box-sizing:border-box;margin:0;padding:0}
html{height:100%}
body{min-height:100%;display:flex;flex-direction:column;align-items:center;background:#faf8f5;color:#1c1917}
h1{font:700 1.85rem/1.15 Hanken\ Grotesk,sans-serif;letter-spacing:-0.03em;margin-bottom:0.55rem}
h2{font:700 1.35rem/1.25 Hanken\ Grotesk,sans-serif;border-top:3px solid #0077b6;padding-top:0.5rem;margin:2.2rem 0 0.8rem}
h3{font:600 1.08rem/1.35 sans-serif;margin:1.6rem 0 0.5rem}
h4{font:600 1rem/1.4 sans-serif;margin:1.2rem 0 0.4rem}
p{margin:0.8rem 0}
ul,ol{margin:0.6rem 0;padding-left:1.4rem}
li{margin:0.35rem 0}
code{font-family:"Baskerville","Hanken Grotesk",monospace;font-size:0.85rem;color:#0f172a;background:#f1f5f9;padding:0.1rem 0.35rem;border-radius:3px}
pre{background:#f1f5f9;padding:1rem;border-radius:6px;overflow-x:auto;margin:1rem 0;border:1px solid #e2e8f0}
pre code{background:none;padding:0}
blockquote{margin:1.2rem 0;padding:0.8rem 1.2rem;border-left:4px solid #0077b6;background:#f8f9fa;font-style:italic;color:#64748b}
hr{border:none;border-top:1px solid #e2e8f0;margin:1.5rem 0}
strong{font-weight:700}em{font-style:italic}
table{width:100%;border-collapse:collapse;margin:1.2rem 0;font-size:0.9rem}
th,td{padding:0.6rem 0.8rem;text-align:left;border:1px solid #e5e7eb}
th{background:#f1f5f9;font-weight:600}
tr:nth-child(even){background:rgb(248,250,252)}
.article{max-width:720px;width:100%;padding:2.5rem 1.5rem;margin:0 auto}
.back{display:inline-block;margin-bottom:1.5rem;color:#64748b;text-decoration:none;font-size:0.9rem}
.meta{color:#6b7280;font-size:0.88rem;margin-bottom:0.5rem}
a{color:#0077b6;text-decoration:none}
a:hover{text-decoration:underline}
img{display:block;max-width:100%;margin:1.5rem auto;border-radius:4px}
figure{margin:1.5rem 0;text-align:center}
figcaption{color:#9ca3af;font-size:0.85rem;margin-top:0.3rem}
footer{margin-top:3rem;padding-top:1rem;border-top:1px solid #e5e7eb;color:#9ca3af;font-size:0.85rem;text-align:center}
"""

def get_title(text):
    m = TITLE_RE.search(text)
    return m.group(1).strip() if m else "Weekly Research"

def generate_html(title, body_html):
    date_str = ""
    dm = DATE_STAMP.search(body_html)
    if dm:
        date_str = f'\n  <p class="meta">{dm.group(0)}</p>'
    return f'''<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>{title}</title>
  <style>
{CSS}
  </style>
</head>
<body>
  <a href="../" class="back">← Back</a>
  <article class="article">
    <header>
      <h1>{title}</h1>{date_str}
    </header>
{body_html}
    <footer><p>Generated by research cron · vadapayasam.github.io/warehouse</p></footer>
  </article>
</body>
</html>
'''

def process_md(path):
    raw = pathlib.Path(path).read_text()
    title = get_title(raw)
    md = markdown.Markdown(extensions=['tables'])
    body = md.convert(raw)
    html = generate_html(title, body)
    slug = slugify(title)
    out = OUTPUT_DIR / f"{slug}.html"
    out.write_text(html)
    return out

def process_existing_html(path):
    """Replaces external CSS with inline styles. Keeps ALL body content."""
    text = pathlib.Path(path).read_text()
    
    # Extract title
    m = re.search(r'<title>(.*?)</title>', text, re.IGNORECASE)
    title = m.group(1) if m else "Weekly Research"
    
    # Replace any <link rel="stylesheet"> with inline <style>
    new_text = re.sub(
        r'<link[^>]*rel="stylesheet"[^>]*>',
        f'<style>\n{CSS}\n  </style>',
        text,
        flags=re.IGNORECASE,
        count=1
    )
    
    # Also fix relative back link if needed
    new_text = new_text.replace('href="../"', 'href="./"')
    
    slug = slugify(title)
    out = OUTPUT_DIR / f"{slug}.html"
    out.write_text(new_text)
    return out

def main(src):
    p = pathlib.Path(src)
    if p.suffix == '.md':
        out = process_md(p)
    elif p.suffix == '.html':
        out = process_existing_html(p)
    else:
        print("ERROR: src must be .md or .html", file=sys.stderr)
        sys.exit(1)

    # Commit/push
    subprocess.run(["git", "add", "sketch/"], cwd=BASE_DIR, check=True)
    subprocess.run(["git", "commit", "-m",
        f"📦 weekly: {out.name}"], cwd=BASE_DIR, check=False)
    subprocess.run(["git", "push"], cwd=BASE_DIR, check=False)
    url = f"https://vadapayasam.github.io/warehouse/sketch/{out.name}"
    print(f"DONE: {out}")
    print(f"URL: {url}")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(f"Usage: {__file__} </path/to/report.md|.html>", file=sys.stderr)
        sys.exit(1)
    main(sys.argv[1])
